/**
 * Datos de siembra: una cocina mediterranea real.
 *
 * Los factores de correccion (`cleaningYield`) son los que se manejan en
 * cocina profesional, no valores inventados para que cuadren los ejemplos. Una
 * alcachofa rinde el 40 % de su peso de compra, un puerro el 60 %, un mejillon
 * el 30 %. Son los numeros que hacen que un escandallo se parezca al albaran.
 *
 * Los precios son de compra al mayorista, por unidad de compra completa y en
 * centimos.
 */

import type { AllergenCode, ItemKind, Unit } from '@warekai/contracts';

export interface SeedItem {
  code: string;
  name: string;
  family: string;
  kinds: ItemKind[];
  purchaseUnitLabel: string;
  stockUnitLabel: string;
  usageUnit: Unit;
  /** Unidades de stock por unidad de compra. */
  purchaseToStock: string;
  /** Unidades de uso por unidad de stock. */
  stockToUsage: string;
  purchasePriceCents: number | null;
  cleaningYield: string;
  densityGPerMl?: string;
  weightPerPieceG?: string;
  vatRate?: string;
  allergens?: Array<{ code: AllergenCode; level: 'CONTAINS' | 'TRACES' }>;
}

/** Jerarquia de familias: [nombre, madre o null]. */
export const SEED_FAMILIES: Array<[string, string | null]> = [
  ['Verduras y hortalizas', null],
  ['Hoja', 'Verduras y hortalizas'],
  ['Raiz y bulbo', 'Verduras y hortalizas'],
  ['Fruto', 'Verduras y hortalizas'],
  ['Setas', 'Verduras y hortalizas'],
  ['Frutas y citricos', null],
  ['Hierbas aromaticas', null],
  ['Pescados y mariscos', null],
  ['Pescado blanco', 'Pescados y mariscos'],
  ['Pescado azul', 'Pescados y mariscos'],
  ['Marisco', 'Pescados y mariscos'],
  ['Carnes', null],
  ['Vacuno', 'Carnes'],
  ['Porcino', 'Carnes'],
  ['Aves', 'Carnes'],
  ['Lacteos y huevos', null],
  ['Despensa', null],
  ['Aceites y vinagres', 'Despensa'],
  ['Especias', 'Despensa'],
  ['Cereales y harinas', 'Despensa'],
  ['Bebidas', null],
  ['Elaboraciones', null],
  ['Platos de carta', null],
];

export const SEED_RAW_ITEMS: SeedItem[] = [
  // --- Verduras y hortalizas -------------------------------------------------
  {
    code: 'VER-001',
    name: 'Alcachofa',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 2250,
    // Se van hojas exteriores, tallo y heno. Es la merma mas brutal de la huerta.
    cleaningYield: '0.40',
    weightPerPieceG: '120',
    vatRate: '0.04',
  },
  {
    code: 'VER-002',
    name: 'Cebolla',
    family: 'Raiz y bulbo',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '1000',
    purchasePriceCents: 890,
    cleaningYield: '0.90',
    weightPerPieceG: '150',
    vatRate: '0.04',
  },
  {
    code: 'VER-003',
    name: 'Ajo',
    family: 'Raiz y bulbo',
    kinds: ['RAW'],
    purchaseUnitLabel: 'malla',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '1',
    stockToUsage: '1000',
    purchasePriceCents: 620,
    // Pelar ajo se lleva casi un cuarto del peso.
    cleaningYield: '0.78',
    weightPerPieceG: '5',
    vatRate: '0.04',
  },
  {
    code: 'VER-004',
    name: 'Tomate pera',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '6',
    stockToUsage: '1000',
    purchasePriceCents: 1140,
    cleaningYield: '0.95',
    weightPerPieceG: '110',
    vatRate: '0.04',
  },
  {
    code: 'VER-005',
    name: 'Pimiento rojo',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 1350,
    cleaningYield: '0.82',
    weightPerPieceG: '200',
    vatRate: '0.04',
  },
  {
    code: 'VER-006',
    name: 'Pimiento verde italiano',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 1080,
    cleaningYield: '0.80',
    weightPerPieceG: '90',
    vatRate: '0.04',
  },
  {
    code: 'VER-007',
    name: 'Calabacin',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 760,
    cleaningYield: '0.90',
    weightPerPieceG: '280',
    vatRate: '0.04',
  },
  {
    code: 'VER-008',
    name: 'Berenjena',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 940,
    cleaningYield: '0.85',
    weightPerPieceG: '300',
    vatRate: '0.04',
  },
  {
    code: 'VER-009',
    name: 'Zanahoria',
    family: 'Raiz y bulbo',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '1000',
    purchasePriceCents: 780,
    cleaningYield: '0.85',
    weightPerPieceG: '90',
    vatRate: '0.04',
  },
  {
    code: 'VER-010',
    name: 'Puerro',
    family: 'Raiz y bulbo',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 1150,
    // Se descarta casi toda la parte verde: rinde poco mas de la mitad.
    cleaningYield: '0.60',
    weightPerPieceG: '220',
    vatRate: '0.04',
  },
  {
    code: 'VER-011',
    name: 'Apio',
    family: 'Hoja',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '4',
    stockToUsage: '1000',
    purchasePriceCents: 860,
    cleaningYield: '0.75',
    weightPerPieceG: '450',
    vatRate: '0.04',
    allergens: [{ code: 'APIO', level: 'CONTAINS' }],
  },
  {
    code: 'VER-012',
    name: 'Patata monalisa',
    family: 'Raiz y bulbo',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '20',
    stockToUsage: '1000',
    purchasePriceCents: 1580,
    cleaningYield: '0.85',
    weightPerPieceG: '180',
    vatRate: '0.04',
  },
  {
    code: 'VER-013',
    name: 'Espinaca fresca',
    family: 'Hoja',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '2',
    stockToUsage: '1000',
    purchasePriceCents: 1120,
    cleaningYield: '0.70',
    vatRate: '0.04',
  },
  {
    code: 'VER-014',
    name: 'Judia verde plana',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 1690,
    cleaningYield: '0.88',
    vatRate: '0.04',
  },
  {
    code: 'VER-015',
    name: 'Calabaza cacahuete',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '8',
    stockToUsage: '1000',
    purchasePriceCents: 1240,
    // Piel dura y pepitas.
    cleaningYield: '0.70',
    vatRate: '0.04',
  },
  {
    code: 'VER-016',
    name: 'Esparrago verde',
    family: 'Fruto',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'manojo',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '500',
    purchasePriceCents: 2400,
    // Se corta el tronco lenoso: se pierde casi la mitad.
    cleaningYield: '0.55',
    vatRate: '0.04',
  },
  {
    code: 'VER-017',
    name: 'Champinon Portobello',
    family: 'Setas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '3',
    stockToUsage: '1000',
    purchasePriceCents: 1450,
    cleaningYield: '0.90',
    weightPerPieceG: '45',
    vatRate: '0.04',
  },
  {
    code: 'VER-018',
    name: 'Seta shiitake',
    family: 'Setas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '2',
    stockToUsage: '1000',
    purchasePriceCents: 3100,
    cleaningYield: '0.88',
    vatRate: '0.04',
  },

  // --- Frutas y citricos -----------------------------------------------------
  {
    code: 'FRU-001',
    name: 'Limon',
    family: 'Frutas y citricos',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '1000',
    purchasePriceCents: 1450,
    // Rendimiento en zumo, que es para lo que se usa en cocina caliente.
    cleaningYield: '0.45',
    weightPerPieceG: '110',
    vatRate: '0.04',
  },
  {
    code: 'FRU-002',
    name: 'Naranja de zumo',
    family: 'Frutas y citricos',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '15',
    stockToUsage: '1000',
    purchasePriceCents: 1650,
    cleaningYield: '0.50',
    weightPerPieceG: '190',
    vatRate: '0.04',
  },
  {
    code: 'FRU-003',
    name: 'Manzana Granny Smith',
    family: 'Frutas y citricos',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '1000',
    purchasePriceCents: 1890,
    cleaningYield: '0.78',
    weightPerPieceG: '175',
    vatRate: '0.04',
  },

  // --- Hierbas ---------------------------------------------------------------
  {
    code: 'HIE-001',
    name: 'Perejil fresco',
    family: 'Hierbas aromaticas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'manojo',
    usageUnit: 'g',
    purchaseToStock: '12',
    stockToUsage: '80',
    purchasePriceCents: 780,
    // Solo se aprovecha la hoja.
    cleaningYield: '0.55',
    vatRate: '0.04',
  },
  {
    code: 'HIE-002',
    name: 'Tomillo fresco',
    family: 'Hierbas aromaticas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'manojo',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '30',
    purchasePriceCents: 950,
    cleaningYield: '0.45',
    vatRate: '0.04',
  },
  {
    code: 'HIE-003',
    name: 'Laurel seco',
    family: 'Hierbas aromaticas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'bolsa',
    stockUnitLabel: 'bolsa',
    usageUnit: 'g',
    purchaseToStock: '1',
    stockToUsage: '250',
    purchasePriceCents: 690,
    cleaningYield: '1',
    vatRate: '0.10',
  },

  // --- Pescados y mariscos ----------------------------------------------------
  {
    code: 'PES-001',
    name: 'Merluza de pincho',
    family: 'Pescado blanco',
    kinds: ['RAW'],
    purchaseUnitLabel: 'pieza',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '3',
    stockToUsage: '1000',
    purchasePriceCents: 4350,
    // Pieza entera a lomo limpio: cabeza, espina y piel fuera.
    cleaningYield: '0.45',
    vatRate: '0.10',
    allergens: [{ code: 'PESCADO', level: 'CONTAINS' }],
  },
  {
    code: 'PES-002',
    name: 'Lubina de estero',
    family: 'Pescado blanco',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '4',
    stockToUsage: '1000',
    purchasePriceCents: 5200,
    cleaningYield: '0.48',
    weightPerPieceG: '450',
    vatRate: '0.10',
    allergens: [{ code: 'PESCADO', level: 'CONTAINS' }],
  },
  {
    code: 'PES-003',
    name: 'Salmon fresco',
    family: 'Pescado azul',
    kinds: ['RAW'],
    purchaseUnitLabel: 'lomo',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '2',
    stockToUsage: '1000',
    purchasePriceCents: 3400,
    cleaningYield: '0.72',
    vatRate: '0.10',
    allergens: [{ code: 'PESCADO', level: 'CONTAINS' }],
  },
  {
    code: 'PES-004',
    name: 'Boqueron',
    family: 'Pescado azul',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '2',
    stockToUsage: '1000',
    purchasePriceCents: 1450,
    cleaningYield: '0.55',
    vatRate: '0.10',
    allergens: [{ code: 'PESCADO', level: 'CONTAINS' }],
  },
  {
    code: 'MAR-001',
    name: 'Pulpo cocido',
    family: 'Marisco',
    kinds: ['RAW'],
    purchaseUnitLabel: 'pieza',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '2',
    stockToUsage: '1000',
    purchasePriceCents: 5600,
    cleaningYield: '0.85',
    vatRate: '0.10',
    allergens: [{ code: 'MOLUSCOS', level: 'CONTAINS' }],
  },
  {
    code: 'MAR-002',
    name: 'Gamba roja de Denia',
    family: 'Marisco',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '1',
    stockToUsage: '1000',
    purchasePriceCents: 9800,
    // Cabeza y caparazon: se queda en la mitad.
    cleaningYield: '0.50',
    weightPerPieceG: '25',
    vatRate: '0.10',
    allergens: [{ code: 'CRUSTACEOS', level: 'CONTAINS' }],
  },
  {
    code: 'MAR-003',
    name: 'Mejillon de roca',
    family: 'Marisco',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 1350,
    // Con concha: la carne es menos de un tercio del peso comprado.
    cleaningYield: '0.30',
    vatRate: '0.10',
    allergens: [{ code: 'MOLUSCOS', level: 'CONTAINS' }],
  },

  // --- Carnes -----------------------------------------------------------------
  {
    code: 'CAR-001',
    name: 'Solomillo de ternera',
    family: 'Vacuno',
    kinds: ['RAW'],
    purchaseUnitLabel: 'pieza',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '2',
    stockToUsage: '1000',
    purchasePriceCents: 6400,
    // Limpiar cordon y telilla.
    cleaningYield: '0.82',
    vatRate: '0.10',
  },
  {
    code: 'CAR-002',
    name: 'Jarrete de ternera',
    family: 'Vacuno',
    kinds: ['RAW'],
    purchaseUnitLabel: 'pieza',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '3',
    stockToUsage: '1000',
    purchasePriceCents: 3900,
    cleaningYield: '0.80',
    vatRate: '0.10',
  },
  {
    code: 'CAR-003',
    name: 'Huesos de ternera para fondo',
    family: 'Vacuno',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '1000',
    purchasePriceCents: 950,
    cleaningYield: '1',
    vatRate: '0.10',
  },
  {
    code: 'CAR-004',
    name: 'Carrillera de cerdo iberico',
    family: 'Porcino',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 4750,
    cleaningYield: '0.88',
    weightPerPieceG: '160',
    vatRate: '0.10',
  },
  {
    code: 'CAR-005',
    name: 'Panceta de cerdo',
    family: 'Porcino',
    kinds: ['RAW'],
    purchaseUnitLabel: 'pieza',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '3',
    stockToUsage: '1000',
    purchasePriceCents: 2100,
    cleaningYield: '0.92',
    vatRate: '0.10',
  },
  {
    code: 'CAR-006',
    name: 'Pollo de corral entero',
    family: 'Aves',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'pieza',
    usageUnit: 'g',
    purchaseToStock: '4',
    stockToUsage: '1800',
    purchasePriceCents: 4200,
    // Despiece a carne limpia.
    cleaningYield: '0.62',
    vatRate: '0.10',
  },

  // --- Lacteos y huevos --------------------------------------------------------
  {
    code: 'LAC-001',
    name: 'Nata liquida 35 % MG',
    family: 'Lacteos y huevos',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'brik',
    usageUnit: 'ml',
    purchaseToStock: '12',
    stockToUsage: '1000',
    purchasePriceCents: 3480,
    cleaningYield: '1',
    densityGPerMl: '1.02',
    vatRate: '0.04',
    allergens: [{ code: 'LACTEOS', level: 'CONTAINS' }],
  },
  {
    code: 'LAC-002',
    name: 'Mantequilla sin sal',
    family: 'Lacteos y huevos',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'pastilla',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '250',
    purchasePriceCents: 3250,
    cleaningYield: '1',
    vatRate: '0.04',
    allergens: [{ code: 'LACTEOS', level: 'CONTAINS' }],
  },
  {
    code: 'LAC-003',
    name: 'Queso manchego curado',
    family: 'Lacteos y huevos',
    kinds: ['RAW', 'SALE'],
    purchaseUnitLabel: 'pieza',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '3',
    stockToUsage: '1000',
    purchasePriceCents: 4200,
    // Se descorteza.
    cleaningYield: '0.90',
    vatRate: '0.10',
    allergens: [{ code: 'LACTEOS', level: 'CONTAINS' }],
  },
  {
    code: 'LAC-004',
    name: 'Queso crema',
    family: 'Lacteos y huevos',
    kinds: ['RAW'],
    purchaseUnitLabel: 'cubo',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '2',
    stockToUsage: '1000',
    purchasePriceCents: 1980,
    cleaningYield: '1',
    vatRate: '0.04',
    allergens: [{ code: 'LACTEOS', level: 'CONTAINS' }],
  },
  {
    code: 'LAC-005',
    name: 'Huevo campero L',
    family: 'Lacteos y huevos',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'docena',
    usageUnit: 'ud',
    purchaseToStock: '15',
    stockToUsage: '12',
    purchasePriceCents: 3150,
    // Cascara.
    cleaningYield: '0.88',
    weightPerPieceG: '63',
    vatRate: '0.04',
    allergens: [{ code: 'HUEVOS', level: 'CONTAINS' }],
  },

  // --- Despensa ------------------------------------------------------------------
  {
    code: 'ACE-001',
    name: 'Aceite de oliva virgen extra',
    family: 'Aceites y vinagres',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'garrafa',
    usageUnit: 'ml',
    purchaseToStock: '3',
    stockToUsage: '5000',
    purchasePriceCents: 12900,
    cleaningYield: '1',
    densityGPerMl: '0.916',
    vatRate: '0.10',
  },
  {
    code: 'ACE-002',
    name: 'Aceite de girasol para fritura',
    family: 'Aceites y vinagres',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'garrafa',
    usageUnit: 'ml',
    purchaseToStock: '3',
    stockToUsage: '5000',
    purchasePriceCents: 5850,
    cleaningYield: '1',
    densityGPerMl: '0.92',
    vatRate: '0.10',
  },
  {
    code: 'ACE-003',
    name: 'Vinagre de Jerez',
    family: 'Aceites y vinagres',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'botella',
    usageUnit: 'ml',
    purchaseToStock: '6',
    stockToUsage: '750',
    purchasePriceCents: 3600,
    cleaningYield: '1',
    densityGPerMl: '1.01',
    vatRate: '0.10',
    allergens: [{ code: 'SULFITOS', level: 'CONTAINS' }],
  },
  {
    code: 'ESP-001',
    name: 'Sal marina fina',
    family: 'Especias',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '1000',
    purchasePriceCents: 780,
    cleaningYield: '1',
    vatRate: '0.10',
  },
  {
    code: 'ESP-002',
    name: 'Pimenton de la Vera dulce',
    family: 'Especias',
    kinds: ['RAW'],
    purchaseUnitLabel: 'lata',
    stockUnitLabel: 'lata',
    usageUnit: 'g',
    purchaseToStock: '1',
    stockToUsage: '750',
    purchasePriceCents: 1290,
    cleaningYield: '1',
    vatRate: '0.10',
  },
  {
    code: 'ESP-003',
    name: 'Azafran en hebra',
    family: 'Especias',
    kinds: ['RAW'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'g',
    usageUnit: 'g',
    purchaseToStock: '10',
    stockToUsage: '1',
    purchasePriceCents: 4500,
    cleaningYield: '1',
    vatRate: '0.10',
  },
  {
    code: 'ESP-004',
    name: 'Pimienta negra en grano',
    family: 'Especias',
    kinds: ['RAW'],
    purchaseUnitLabel: 'bolsa',
    stockUnitLabel: 'bolsa',
    usageUnit: 'g',
    purchaseToStock: '1',
    stockToUsage: '500',
    purchasePriceCents: 1450,
    cleaningYield: '1',
    vatRate: '0.10',
  },
  {
    code: 'CER-001',
    name: 'Harina de trigo floja',
    family: 'Cereales y harinas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '25',
    stockToUsage: '1000',
    purchasePriceCents: 2150,
    cleaningYield: '1',
    vatRate: '0.04',
    allergens: [{ code: 'GLUTEN', level: 'CONTAINS' }],
  },
  {
    code: 'CER-002',
    name: 'Arroz bomba',
    family: 'Cereales y harinas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 2950,
    cleaningYield: '1',
    vatRate: '0.04',
  },
  {
    code: 'CER-003',
    name: 'Pan de hogaza',
    family: 'Cereales y harinas',
    kinds: ['RAW', 'SALE'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'hogaza',
    usageUnit: 'g',
    purchaseToStock: '8',
    stockToUsage: '500',
    purchasePriceCents: 1440,
    cleaningYield: '1',
    vatRate: '0.04',
    allergens: [
      { code: 'GLUTEN', level: 'CONTAINS' },
      { code: 'SESAMO', level: 'TRACES' },
    ],
  },
  {
    code: 'CER-004',
    name: 'Almendra marcona repelada',
    family: 'Cereales y harinas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '5',
    stockToUsage: '1000',
    purchasePriceCents: 6900,
    cleaningYield: '1',
    vatRate: '0.10',
    allergens: [{ code: 'FRUTOS_DE_CASCARA', level: 'CONTAINS' }],
  },
  {
    code: 'CER-005',
    name: 'Azucar blanquilla',
    family: 'Cereales y harinas',
    kinds: ['RAW'],
    purchaseUnitLabel: 'saco',
    stockUnitLabel: 'kg',
    usageUnit: 'g',
    purchaseToStock: '15',
    stockToUsage: '1000',
    purchasePriceCents: 1780,
    cleaningYield: '1',
    vatRate: '0.10',
  },

  // --- Bebidas -------------------------------------------------------------------
  /**
   * El caso que justifica el modelo de item unico: el mismo vino entra en el
   * fondo oscuro como materia prima y se sirve por copas como articulo de
   * venta. Con tres entidades separadas habria que duplicarlo y mantener dos
   * precios de compra sincronizados a mano.
   */
  {
    code: 'BEB-001',
    name: 'Vino blanco Verdejo',
    family: 'Bebidas',
    kinds: ['RAW', 'SALE'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'botella',
    usageUnit: 'ml',
    purchaseToStock: '6',
    stockToUsage: '750',
    purchasePriceCents: 3150,
    cleaningYield: '1',
    densityGPerMl: '0.99',
    vatRate: '0.21',
    allergens: [{ code: 'SULFITOS', level: 'CONTAINS' }],
  },
  {
    code: 'BEB-002',
    name: 'Vino tinto Ribera del Duero',
    family: 'Bebidas',
    kinds: ['RAW', 'SALE'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'botella',
    usageUnit: 'ml',
    purchaseToStock: '6',
    stockToUsage: '750',
    purchasePriceCents: 5400,
    cleaningYield: '1',
    densityGPerMl: '0.99',
    vatRate: '0.21',
    allergens: [{ code: 'SULFITOS', level: 'CONTAINS' }],
  },
  {
    code: 'BEB-003',
    name: 'Agua mineral 50 cl',
    family: 'Bebidas',
    kinds: ['RAW', 'SALE'],
    purchaseUnitLabel: 'caja',
    stockUnitLabel: 'botella',
    usageUnit: 'ml',
    purchaseToStock: '24',
    stockToUsage: '500',
    purchasePriceCents: 720,
    cleaningYield: '1',
    densityGPerMl: '1',
    vatRate: '0.10',
  },
];
